name: sensors_example
description: Demonstrates how to use the sensors plugin.
environment:
  sdk: ">=2.12.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #sensors: ^0.4.0+1
  sensors: ^2.0.3

flutter:

  uses-material-design: true
